- name: SSH into EC2 and run deployment script
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SERVER_IP }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    hostkey: ${{ secrets.SERVER_HOSTKEY }}
    script: |
      /opt/deploy.sh
